import { APPNAME } from '../../lib/Utils'

export const SET_LOCATION = APPNAME + '/translate/SET_LOCATION'

export const fullTraslate = {
  en: {
    activate: 'Activate',
    activity: 'Activity',
    activity_to_today: 'Activity For Today',
    add: 'Add',
    address: 'Address',
    administration: 'Administration',
    alert_holiday: 'You Must Select A Country',
    alert_vacations: 'Vacations Must Assign A Consultant',
    amount: 'Amount',
    answers: 'Answers',
    aprove: 'Aprove',
    aprove_by: 'Aprove By',
    aprove_expens: 'Aprove Expens',
    aprove_extend_message: 'Surely you want to accept this extension, if the task has an impact on the project could increase its duration',
    aprove_hour_message: 'Insurance To Approve This Hour',
    assign_activity: 'Assign Activity',
    avatar: 'Photo Profile',
    bar_code: 'Bar Code',
    basic_information: 'Basic Information',
    before_long: 'Before Long',
    change_my_info: 'Change My Info',
    change_password: 'Change password',
    chat_title: 'OnBusiness Consulting',
    city: 'city',
    close: 'Close',
    consultant: 'Consultant',
    consultant_by_project: 'Consultant By Project',
    consulting_view: 'Consultant View',
    consumer_tax: 'Consumer Tax',
    contact: 'Contact',
    contact_email: 'Contact Email',
    contact_number: 'Contact Number',
    cost_center: 'Cost Center',
    country: 'Country',
    create: 'Create',
    creator: 'creator',
    currency: 'Currency',
    customer: 'Customer',
    customer_user_need_customer: 'Customer User Need Customer',
    date: 'Date',
    days: 'Days',
    delete: 'Delete',
    delete_activity: 'Sure You Want To Eliminate This Activity',
    delete_holiday: 'Insurance To Eliminate These Holiday',
    delete_request: 'Are You Really Sure To Erase This Request Permanently',
    delete_user: 'Are You Really Sure To Erase This User Permanently',
    delete_vacations: 'Insurance To Eliminate These Vacations',
    desactivate: 'Desactivate',
    description: 'Description',
    duration: 'Duration',
    edit: 'Edit',
    email: 'Email',
    end_date: 'End Date',
    end_hour: 'End Hour',
    expenses: 'Expenses Travin',
    extend: 'Extend',
    extend_to_aprove: 'Extend To Aprove',
    extra_hour: 'Extra Hours',
    forget_password: 'Forget Your Password?',
    form: 'Form',
    free: 'Free',
    free: 'Free',
    free_consulting_list: 'Free Consulting List',
    free_in: 'Free In:',
    free_today: 'Free Tday',
    grafic: 'Grafic',
    half: 'Half',
    has_activity: 'sorry you have activities for this day in: ',
    height: 'Height',
    holiday: 'Holiday',
    hours: 'Hours',
    hours_aprove: 'Hours Aprove',
    hours_no_project: 'Hours No In Project',
    hours_project: 'Hours To Project',
    hours_to_aprove: 'Hours To Aprove',
    incident: 'Incident',
    is_a_new_project: 'Is A New Project?',
    is_staff: 'is PM',
    iva: 'IVA',
    last_activity_at: 'Last Activity: ',
    last_name: 'Last Name',
    last_time_record_hour: 'Last Time Record Hour',
    legal: 'Legal',
    list: 'List',
    listMonth: ['January','February','March','April','May','June','July','August','September','October','Novembre','December'],
    login: 'Login',
    logout: 'Logout',
    loose_hours: 'Activitys no in Project',
    low: 'Low',
    mail_can_sent: 'Email Cant Send',
    manage: 'Manage',
    manager: 'Manager',
    member: 'Member',
    month: 'Month',
    months: 'Months',
    motive: 'Motive',
    motive_refuse: 'Reason For Rejection',
    must_have_member: 'Must Have Member',
    must_have_role: 'Must Have Role',
    name: 'Name',
    natural: 'Natural',
    need_activity: 'Need Activity',
    need_activity_name: 'need activity name',
    need_add_picture: 'Previous Image Display If Required',
    need_member: 'Need Member',
    need_name_activity: 'The Activity Must Have A Name',
    need_name_pahse: 'The Phase Must Have A Name',
    need_need_define_all_member: 'need define all member',
    need_phase: 'Need Phase',
    need_project: 'need project',
    need_project: 'need project',
    need_project_name: 'need project name',
    new2: 'New',
    new: 'New',
    new_password: 'New password',
    nit: 'Nit',
    no_day: 'sorry you have no added activities for this date in the project ',
    no_project: 'NO PROJECT',
    no_ready_code: 'Can Not Read Any Bar Code Try Again',
    no_user_found: 'User No Found',
    not_found: 'Not Found',
    notify_my_mail: 'Notify To My Mail?',
    number_days: 'Number days',
    number_days: 'number days',
    number_hours: 'Number Hours',
    occupation: 'Occupation',
    old_password: 'Old password',
    old_password_error: 'Old password Incorrect',
    only_one_day: 'Only One Day',
    option_holiday: 'HOLIDAY',
    other: 'OTHER',
    password: 'Password',
    pending: 'Pending',
    person: 'Person',
    phase: 'Phase',
    phone: 'Phone',
    phone_number: 'Phone Number',
    photo: 'Photo',
    pm_view: 'PM View',
    previous_activity: 'Parent Activity',
    previous_phase: 'Previous Phase',
    priority: 'Priority',
    profile: 'Profile',
    project: 'Project',
    project_by_consultant: 'Project By Consultant',
    provider: 'Provider',
    quantity: 'quantity',
    red_field_is_required: 'Red Field Is Required',
    refuse: 'refuse',
    refuse_expens: 'Refuse Expens',
    refuse_extend_message: 'Sure You Want To Reject This Extent',
    refuse_hour_message: 'You Must Specify A Reason To Reject An Hour',
    repeat_new_password: 'Repeat New password',
    repeat_new_password_error: 'Passwords Do Not Match',
    reporst: 'Reporst',
    requests: 'requests',
    required: 'Required',
    reset_password: 'Reset Password',
    resource: 'Resource',
    responsable: 'Responsable',
    rest: 'Rest',
    role: 'Role',
    schedule: 'Schedule',
    search: 'Search',
    see: 'See',
    select_a_activity: 'Select A Activity',
    select_a_consultant: 'Select A Consultant',
    select_a_country: 'Select A Country',
    select_a_customer: 'Select A Customer',
    select_a_manager: 'Select A Manager',
    select_a_member: 'Select A Member',
    select_a_occupation: 'Select A Occupation',
    select_a_phase: 'Select A Phase',
    select_a_projectTypologys: 'Select A project Typology',
    select_a_previous_activity: 'Select A Parent Activity',
    select_a_project: 'Select A Project',
    select_a_provider: 'Select A Provider',
    select_a_reporst: 'Select A Report',
    select_a_resource: 'Select A Resource',
    select_a_role: 'Select A Role',
    select_previous_phase: 'Select A Phase If This Face Has A Preview',
    send_mail: 'Send Mail',
    start_date: 'Start Date',
    start_hour: 'Start Hour',
    state: 'State',
    status: 'Status',
    sub_total: 'Sub Total',
    subject: 'Subject',
    table: 'Table',
    to: 'To',
    trading: 'trading',
    training: 'TRAINING',
    type: 'Type',
    type_user: 'type user',
    unlink: 'Unlink',
    upload_excel: 'Upload Excel',
    upload: 'Upload',
    uploanding: 'Uploanding',
    user: 'User',
    username_input: 'Enter User or Email',
    vacation: 'Vacation',
    vacations: 'Vacations',
    viewed: 'Viewed',
    week: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
    weeks: 'Weeks',
    welcome: 'Welcome',
    work_day: 'WORK DAY',
    year: 'Year',
    observations: 'Observations',
    project_name: 'Project Name',
    file: 'file',
    project_management: 'Project Management',
    avanced: 'Avanced',
    weeks_number: 'Weeks Number',
    estimated: 'Estimated',
    real: 'Real',
    multi_activity: 'Multi Activity',
    no_customer: 'No Customer',
    calendar: 'Calendar',
    save: 'Save',
    delete_country_message: 'Are You Sure To Delete This Country?',
    roles: 'Rol´s',
    chart: 'Chart',
    select_a_cost_center: 'Select A Cost Center',
    need_cost_center: 'Need Cost Center',
    activity_no_phase: 'Activitys No In Phase',
    delete_costCenter_message: 'Delete this Cost Center?',
    code: 'Code',
    select_a_state: 'Select A State',
    select_a_city: 'Select A City',
    register_activity: 'Register Activity',
    name_activity: 'Activity Name',
    is_a_new_phase: 'Is A New Phase?',
    name_phase: 'Phase Name',
    P: 'Pending',
    A: 'Approved',
    R: 'Rejected',
    all: 'All',
    report_hours_week: 'Report Hours Week',
    weeks: 'Week',
    date_of_admission: 'Date Of Admission',
    users_date_of_admission: 'Resource Date Of Admission',
    request_vacations: 'Request Vacations',
    action_loock: 'Action Loock',
    refuse_request: 'Refuse Request of ',
    closed: 'Closed',
    opened: 'Open',
    archived: 'Archived',
    activitys: 'Activitys',
    add_activitys_member: 'Add Activitys To',
    unlink_member_activity: 'Unlink Activity Member',
    delete_record_of_hour: 'Delete Record Of Hour?',
    type_project: 'Type',
    close_project_message: 'you want to archive this project once it is archived you can not modify it',
    delete_project_message: 'you want delete this project',
    category: 'Category',
    project_typology: 'Project Typology',
    no_project_typology: 'No Project Typology',
    support: 'Support',
    enjoy: 'Enjoy',
    severity:'Severity',
    periodicity:'Periodicity',
    staeps_to_reproduce: 'Staeps To Reproduce',
    atditional_information: 'Atditional Information',
    allways: 'Allways',
    sometimes: 'Sometimes',
    random: 'Random',
    not_have_trigger: 'Not Have Srigger',
    loock: 'Loock',
    impossible_to_reproduce: 'Impossible To Reproduce',
    select_a_category: 'Select A Category',
    'N/A': 'N/A',
    report_status_reasource: 'Status Reasource',
    assigned: 'Assigned',
    delete_incident: 'Are You Really Sure Delete This Incidents?',
    tracking: 'Tracking',
    delete_tracking: 'are you sure delete this tracking?',
    search_by_name: 'Search By Name Project',
    file_project_message: 'Do You Wanna filed this project?',
    delete_hour_message: 'Delete This Hours?',
    document: 'Document',
    solution: 'Solution',
    select_a_solution: 'Select A Solution',
    is_fixed: 'Is Fixed',
    start_project: 'Start Project',
    end_project: 'End Project',
    start_activity: 'Start Activity',
    end_activity: 'End Activity',
    estimated: 'Estimated',
    deviation: 'Deviation',
    report_status_project: 'Report Status Project',
    aprove_select: 'Aprove Select',
    refuse_select: 'Refuse Select',
    uploadExcelBalance: 'Upload Excel Balance',
    uploading: 'Uploading',
    car: 'Car',
    my_order: 'My Order',
    all_order: 'All Order',
    register: 'Register',
    about: 'About',
    team: 'Team',
  },

  es: {
    team: 'Equipo',
    about: 'Acerca De',
    register: 'Registrar',
    all_order: 'Todas Las Ordenes',
    my_order: 'Mis Ordenes',
    car: 'Carrito',
    uploading: 'Subiendo',
    uploadExcelBalance: 'Subir Balance Contable Excel',
    refuse_select: 'Recazar Las Selecionadas',
    aprove_select: 'Aprobar Las Selecionadas',
    report_status_project: 'Reporte Estatus De Los Proyectos',
    deviation: 'desviación',
    estimated: 'Estimado',
    start_project: 'Proyecto Inicial',
    end_project: 'Poyecto Final',
    start_activity: 'Actividad Inicial',
    end_activity: 'Actividad Final',
    is_fixed: 'Esta Fijada',
    select_a_solution: 'Selecciona Una Solution',
    solution: 'Solución',
    document: 'Documento',
    delete_hour_message: '¿Eliminar Esta Hora?',
    file_project_message: '¿Dessea Archivar Este Poryecto?',
    search_by_name: 'Buscar Por Nombre Del Proyecto',
    delete_tracking: '¿Está Seguro De Eliminar Este Seguimiento?',
    tracking: 'Seguimiento',
    delete_incident: '¿Esta Realmente Seguro De Eliminar Este Incidente',
    assigned: 'Asignado',
    report_status_reasource: 'Estado De Recurso',
    'N/A': 'N/A',
    select_a_category: 'Seleccione Una Categoría',
    impossible_to_reproduce: 'Imposible Reproducir',
    loock: 'Bloquedora',
    not_have_trigger: 'No Tiene Un Disparador Definido',
    random: 'Aleatorio',
    sometimes: 'A Veces',
    allways: 'Siempre',
    staeps_to_reproduce: 'Pasos Para Reproducir',
    atditional_information: 'Información Adicional',
    severity:'Severidad',
    periodicity:'Periodicidad',
    enjoy: 'En Disfrute',
    support: 'Soporte',
    no_project_typology: 'Sin Tipología De Proyecto',
    select_a_projectTypologys: 'Selecciona Una Tipología De Proyecto',
    project_typology: 'Tipologia De Proyecto',
    category: 'Categoria',
    delete_project_message: 'Desea Eliminar Este Project',
    close_project_message: 'deseas archivar este proyecto una vez archivado no se podrá modificar',
    type_project: 'Tipo',
    delete_record_of_hour: '¿Eliminar Este Registros De Horas?',
    unlink_member_activity: 'Desvincular Miembro De La Actividad',
    add_activitys_member: 'Agregar Actividades A',
    activitys: 'Actividades',
    archived: 'Archivados',
    opened: 'Abiertos',
    closed: 'Cerrados',
    refuse_request: 'Rechazar El Requerimiento De ',
    action_loock: 'Accion Bloqueada',
    request_vacations: 'Solicitar Vacaciones',
    users_date_of_admission: 'Administras Fechas De ingreso',
    date_of_admission: 'Fecha De Ingreso',
    weeks: 'Semana',
    report_hours_week: 'Reportes De Horas Semanales',
    all: 'Todos',
    R: 'Rechazado',
    A: 'Aprobado',
    P: 'Pendiente',
    name_phase: 'Nombre De La Fase',
    is_a_new_phase: '¿Es Una Nueva Fase?',
    name_activity: 'Nombre De La Actividad',
    register_activity: 'Registrar Actividad',
    select_a_state: 'Selecciona Un Estado',
    select_a_city: 'Selecciona Una Ciudad',
    code: 'Codigo',
    delete_costCenter_message: '¿Eliminar Este Centro De Costo?',
    activity_no_phase: 'Actividades Que No Están En Una Fase',
    need_cost_center: 'Necesitas Un Centro De Costo',
    select_a_cost_center: 'Selecciona Un Centro De Costo',
    chart: 'Grafico',
    roles: 'Roles',
    delete_country_message: '¿Está Seguro De Eliminar Este País?',
    save: 'Guardar',
    calendar: 'Calendario',
    no_customer: 'Sin Cliente',
    multi_activity: 'Multi Actividades',
    weeks_number: 'Numero De Semana',
    estimated: 'Estimado',
    real: 'Real',
    avanced: 'Avance',
    project_management: 'Gestión De Proyecto',
    file: 'Archivar',
    project_name: 'Nombre Del Proyecto',
    observations: 'Observaciones',
    activate: 'Activar',
    activity: 'Actividad',
    activity_to_today: 'Actividades Para Hoy',
    add: 'Agregar',
    address: 'Dirección',
    administration: 'Administración',
    alert_holiday: 'Debes Seleccionar Un País',
    alert_vacations: 'Las Vacaciones Se Debe Asignar A Un consultor',
    amount: 'Monto',
    answers: 'Respuestas',
    aprove: 'Aprobar',
    aprove_by: 'Aprobado Por',
    aprove_expens: 'Aprobar Gasto',
    aprove_extend_message: 'Seguro Que Desea Aceptar Esta Extensión, Si La Tarea Tiene Impacto En El Proyecto Podría aumentar su Duración',
    aprove_hour_message: 'Seguro De Aprobar Esta Hora',
    assign_activity: 'Actividades Asignadas',
    avatar: 'Foto De Perfil',
    bar_code: 'Codigo De Barra',
    basic_information: 'Información Básica',
    before_long: 'Próximamente',
    change_my_info: 'Cambiar Mi Información',
    change_password: 'Cambiar Contraseña',
    chat_title: 'OnBusiness Consulting',
    city: 'Ciudad',
    close: 'Cerrar',
    consultant: 'Consultor',
    consultant_by_project: 'Consultores Por Proyecto',
    consulting_view: 'Vista Consultor',
    consumer_tax: 'Impuesto Al Consumidor',
    contact: 'Contacto',
    contact_email: 'Email De Contacto',
    contact_number: 'Numero De Contacto',
    cost_center: 'Centro De Costo',
    country: 'País',
    create: 'Crear',
    creator: 'Creador',
    currency: 'Moneda',
    customer: 'Cliente',
    customer_user_need_customer: 'Usuarios Tipo Cliente Necesitan Un Cliente Asociado',
    date: 'Fecha',
    days: 'Dias',
    delete: 'Eliminar',
    delete_activity: 'Seguro Que Desea Eliminar Esta Actividad',
    delete_holiday: 'Seguro De Eliminar Este Feriado',
    delete_request: 'Esta Realmente Seguro De Borrar Este Requerimiento Permanentemente',
    delete_user: 'Esta Realmente Seguro De Borrar Este Usuario Permanentemente',
    delete_vacations: 'Seguro De Eliminar Estas Vacaciones',
    desactivate: 'Desactivar',
    description: 'Descripción',
    duration: 'Duración',
    edit: 'Editar',
    email: 'Correo',
    end_date: 'Fecha Fin',
    end_hour: 'Hora De Fin',
    expenses: 'Gastos De Viaje',
    extend: 'Estencion',
    extend_to_aprove: 'Extensiones Por Aprobar',
    extra_hour: 'Horas Extras',
    forget_password: '¿Olvidaste tu Contraseña?',
    form: 'Formulario',
    free: 'Libre',
    free: 'Libres',
    free_consulting_list: 'Lista De Consultores Libres',
    free_in: 'libre en:',
    free_today: 'Libres Hoy',
    grafic: 'Grafico',
    half: 'Media',
    has_activity: 'lo siente tienes actividades para este día en: ',
    height: 'Alta',
    holiday: 'Feriados',
    hours: 'Horas',
    hours_aprove: 'Horas Aprobadas',
    hours_no_project: 'Hora No Asociada A Una Actividad',
    hours_project: 'Horas A Un Proyecto',
    hours_to_aprove: 'Horas Por Aprobar',
    incident: 'Incidentes',
    is_a_new_project: '¿Es Un Nuevo Proyecto?',
    is_staff: 'Es PM',
    iva: 'IVA',
    last_activity_at: 'Ultima Actividad En: ',
    last_name: 'Apellido',
    last_time_record_hour: 'Ultima Hora Aprobada',
    legal: 'Jurídica',
    list: 'Lista',
    listMonth: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
    login: 'Iniciar Sesión',
    logout: 'Cerrar Sesión',
    loose_hours: 'Actividades Independientes',
    low: 'Baja',
    mail_can_sent: 'El Correo No Se Pudo Enviar',
    manage: 'Administrar',
    manager: 'Manager',
    member: 'Miembro',
    month: 'Mes',
    months: 'Meses',
    motive: 'Motivo',
    motive_refuse: 'Motivo De Rechazo',
    must_have_member: 'El Proyecto Debe Tener Un Miembro',
    must_have_role: 'Debe Tener Un Rol',
    name: 'Nombre',
    natural: 'Natural',
    need_activity: 'Necesitas Una Actividad',
    need_activity_name: 'La Actividad Necesita Un Nombre',
    need_add_picture: 'Previa Visualización De La Imagen Si Es Requerido',
    need_member: 'Necesitas Asignarle Un Miembro A La Tarea',
    need_name_activity: 'La Actividad Debe Tener Un Nombre',
    need_name_pahse: 'La Fase Debe Tener Un Nombre',
    need_need_define_all_member: 'Necesitas Definir A Todos Los Miembros',
    need_phase: 'Necesitas Seleccionar Una Fase',
    need_project: 'Necesitas Seleccionar Un Proyecto',
    need_project_name: 'Necesitas Darle Nombre al Proyecto',
    new2: 'Nueva',
    new: 'Nuevo',
    new_password: 'Nueva Contraseña',
    nit: 'Nit',
    no_day: 'lo siente no tiene agregado actividades para esta fecha en el proyecto ',
    no_project: 'NO PROYECTO',
    no_ready_code: 'No Se Pudo Leer Ningún Código De Barra Intente De Nuevo',
    no_user_found: 'Usuario No encontrado',
    not_found: 'No Encontrado',
    notify_my_mail: '¿Notificar a mi correo?',
    number_days: 'Número De Días',
    number_days: 'Números De Días',
    number_hours: 'Número De Horas',
    occupation: 'Ocupación',
    old_password: 'Antigua Contraseña',
    old_password_error: 'Antigua Contraseña Incorrecta',
    only_one_day: 'Dura Solo Un Día',
    option_holiday: 'FERIADO',
    other: 'OTROS',
    password: 'Contraseña',
    pending: 'Pendiente',
    person: 'Persona',
    phase: 'Fase',
    phone: 'Teléfono',
    phone_number: 'Numero De Teléfono',
    photo: 'Foto',
    pm_view: 'Vista PM',
    previous_activity: 'Actividad Padre',
    previous_phase: 'Fase Previa',
    priority: 'Prioridad',
    profile: 'Perfil',
    project: 'Proyecto',
    project_by_consultant: 'Proyectos Por Consultores',
    provider: 'Proveedor',
    quantity: 'Cantidad',
    red_field_is_required: 'Los Campo rojos Son Requeridos',
    refuse: 'Rechazar',
    refuse_expens: 'Rechazar Gasto',
    refuse_extend_message: 'Seguro Que Desea Rechazar Esta Extensión',
    refuse_hour_message: 'Debes Especificar Un Motivo Para Rechazar Una Hora',
    repeat_new_password: 'Repita Nueva Contraseña',
    repeat_new_password_error: 'Contraseña No Coinciden',
    reporst: 'Reportes',
    requests: 'Requerimiento',
    required: 'Requerido',
    reset_password: 'Reiniciar Contraseña',
    resource: 'Recurso',
    responsable: 'Responsable',
    rest: 'Inactividad',
    role: 'Rol',
    schedule: 'Cronograma',
    search: 'Buscar',
    see: 'Ver',
    select_a_activity: 'Selecciona Una Tarea',
    select_a_consultant: 'Seleccione Un Consultor',
    select_a_country: 'Seleccione Un País',
    select_a_customer: 'Seleccione Un Cliente',
    select_a_manager: 'Seleccione Un Manager',
    select_a_member: 'selecciona Un Miembro Del Proyecto',
    select_a_occupation: 'Selecciona Una Ocupación',
    select_a_phase: 'selecciona Una Fase',
    select_a_previous_activity: 'selecciona Una Actividad Padre',
    select_a_project: 'Seleccione Un Proyecto',
    select_a_provider: 'Selecciona A Un Proveedor',
    select_a_reporst: 'Seleccione Un Reporte',
    select_a_resource: 'Seleccione Un Recurso',
    select_a_role: 'Seleccione Un Rol',
    select_previous_phase: 'seleccione Una Fase Si Esta Fase tiene Una Previa',
    send_mail: 'Enviando Correo',
    start_date: 'Fecha Inicio',
    start_hour: 'Hora De Inicio',
    state: 'Estado',
    status: 'Estado',
    sub_total: 'Sub Total',
    subject: 'Asunto',
    table: 'Tabla',
    to: 'Para',
    total: 'Total',
    total: 'Total',
    trading: 'Comercial',
    training: 'CAPACITACION',
    type: 'Tipo',
    type_user: 'Tipo De Recurso',
    unlink: 'Desvincular',
    upload_excel: 'Subir Excel',
    upload: 'Subir',
    uploanding: 'Subiendo',
    user: 'Usuario',
    username_input: 'Ingrese Usuario O Correo Electrónico',
    vacation: 'Vacacion',
    vacations: 'Vacaciones',
    viewed: 'Visto',
    week: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
    weeks: 'Semanas',
    welcome: 'Bienvenido',
    work_day: 'DIA DE TRABAJO',
    year: 'Año',
  }
}

const initialStates = {
  location: 'es',
  translateFull: fullTraslate,
  translate: fullTraslate['es']
}

export default function reducer (state = initialStates, action) {
  switch (action.type) {
    case SET_LOCATION:
      return {
        ...state,
        location: action.location,
        translate: action.translate
      }
      break
    default:
      return state
      break
  }
}
